export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_GET_PRODUCTS = "START_GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const GET_DELETE_PRODUCT = 'GET_DELETE_PRODUCT';
export const DELETED_PRODUCT_SUCCESS = 'DELETED_PRODUCT_SUCCESS';
export const DELETED_PRODUCT_ERROR = 'DELETED_PRODUCT_ERROR';

export const GET_EDIT_PRODUCT = 'GET_EDIT_PRODUCT';
export const START_EDIT_PRODUCT = 'START_EDIT_PRODUCT';
export const EDITED_PRODUCT_SUCCESS = 'EDITED_PRODUCT_SUCCESS';
export const EDITED_PRODUCT_ERROR = 'EDITED_PRODUCT_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';