export const NEW_PROJECT_FORM = 'NEW_PROJECT_FORM';
export const OBTAIN_PROJECTS = 'OBTAIN_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const ACTUAL_PROJECT = 'ACTUAL_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const PROJECT_ERROR = 'PROJECT_ERROR';

export const PROJECT_TASKS = 'PROJECT_TASKS';
export const ADD_TASKS = 'ADD_TASKS';
export const VALIDATE_TASK = 'VALIDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const SELECT_TASK = 'SELECT_TASK';
export const CLEAN_TASK = 'CLEAN_TASK';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const SUCCESS_REGIST = 'SUCCESS_REGIST';
export const FAILURE_REGIST = 'FAILURE_REGIST';
export const GET_USER = 'GET_USER';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const FAILURE_LOGIN = 'FAILURE_LOGIN';
export const CLOSE_SESSION = 'CLOSE_SESSION';