export const NEW_PROJECT_FORM = 'NEW_PROJECT_FORM';
export const OBTAIN_PROJECTS = 'OBTAIN_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const ACTUAL_PROJECT = 'ACTUAL_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';